### ISSUE TITLE
Metadata not shown for non-admin users

### ISSUE THREAD

**Issue by paulijar** [gino0631/nextcloud-metadata#1]
I really like the idea of this app and I think it fills an important gap in Nextcloud. However, it seems to me that it can currently show metadata of image files only for the admin user. As admin, I have no problems viewing metadata of any of my image files. But if I log in as any non-admin user, then the Metadata tab stays indefinitely in the state "Reading metadata ..." on all files. In Chrome, the browser console shows an error like `jquery.js:8630 GET https://xxxxxxxxxx.xxx/nextcloud/index.php/apps/metadata/get?source=%2FPhotos%2FSquirrel.jpg 403 (Forbidden)`. In Firefox, there is no errors in the console.

Tested on Nextcloud 12.

**Comment by xraMsamohT** [comment]
Nextcloud log on _debug level_ shows the error: "Logged in user must be an admin"

**Comment by gino0631** [comment]
Thank you for the feedback! This should be fixed in 0.2.0, please test and let me know the results.

**Comment by xraMsamohT** [comment]
Works with Nextcloud `11.0.3.2` and `12.0.1.4`.

**Comment by paulijar** [comment]
Retested on 0.2.0 and works great now. Cheers!

**Comment by mfilocha** [comment]
Version 0.3.0 works well with NextCloud 12.0.1 except the "Location" line. Message "Resolving, click here to view on map" is displayed for non-admin users.

**Comment by mfilocha** [comment]
Update: The issue described above might be a Nominatim problem, not app itself: _The server is temporarily unable to service your request due to maintenance downtime or capacity problems. Please try again later._

**Comment by gino0631** [comment]
Might be. I'll try to implement a better handling of such situations.
