### ISSUE TITLE
Add Nextcloud 28.x Compatibility.

### ISSUE THREAD

**Issue by roliverio** [gino0631/nextcloud-metadata#105]
Quick issue to update the app to support Nextcloud 28.x onwards. Thanks!

**Comment by gino0631** [comment]
@roliverio thanks for the reminder.

**Comment by RainerEmrich** [comment]
> @roliverio thanks for the reminder.
ping

**Comment by Chrispikaan** [comment]
Is there an update on this? I really like this app, but it isn't working right now.

**Comment by gino0631** [comment]
Apologies for the delay, but this time it will take longer as there are more changes in the Nextcloud itself.

**Comment by galandilias** [comment]
Any progress on this one?

**Comment by gino0631** [comment]
@galandilias thanks for the ping. Unfortunately, still no, though I hope to make it this month.

**Comment by gino0631** [comment]
@plaes the first version of your message named the reasons correctly.

> Firstly, the real cause for this issue: OCA.Files.FileList was a private API that app developers should not have relied upon.

This has nothing to do with the issue.

As for the Vue, yes, the support for the non-Vue sidebar apps was silently removed, which is the biggest problem for now.

**Comment by immanuelfodor** [comment]
I regularly get these log lines over and over, this probably has to do with compatibility:
`"message":"Could not boot metadata: Call to undefined method OC\\Server::getEventDispatcher()"`

**Comment by gino0631** [comment]
@immanuelfodor yes, this was already reported in #106

**Comment by PeterLue** [comment]
The same error message was displayed in another  project (OCCWEB). The solution here was the call
OC::$server->getEventDispatcher(),
through
OC::$server->get(\OCP\EventDispatcher\IEventDispatcher::class),
to replace. Just for info.

**Comment by gino0631** [comment]
@nooblag yes, you can try disabling the app meanwhile

**Comment by aliyasiny65** [comment]
Hello, when will nextcloud 28 compatibility come?

**Comment by Ch3ck3rM0n** [comment]
> > I regularly get these log lines over and over, this probably has to do with compatibility: `"message":"Could not boot metadata: Call to undefined method OC\\Server::getEventDispatcher()"`
> 
> Hi there, thanks for a great app. Just reporting I get lots of these in the logs with Nextcloud 28. Reading this thread, sounds like work is still ongoing for an update, so thank you. 😄

I having the same output in the logs/issue with the app. I am also waiting for an update :-/

**Comment by SKB-CGN** [comment]
In the meanwhile you can use the Memories App, to display the metadata.

**Comment by yeupou** [comment]
Hi there,

I noticed no problem with the metadata app on NC 28 since a few month, besides the massive log noise output.

Is it possible to get the app uploaded with PeterLue fix, in the meantime?

Thanks.

**Comment by roliverio** [comment]
I've just received notice of the close-by release of NC 29.xx and this app hasn't had updates for v28. Do you plan on still maintaining it?. Thanks for any update.

**Comment by gino0631** [comment]
@roliverio thanks for the ping. No, this app is not abandoned. As for Nextcloud, I'm seriously disappointed, and personally decided just not to upgrade, as it only gets worse with every new release (though I haven't found any suitable replacement so far). The works on the app depend on free time I have, and therefore don't go smoothly sometimes (especially when the workload is higher due to the nature of changes in Nextcloud).

**Comment by gino0631** [comment]
@yeupou are you sure the app is working for you on NC 28?

**Comment by roliverio** [comment]
@gino0631 I understand and i don't blame you at all. I do love your work, and i appreciate the existence of this app, however, i can't deny that i'm blocked from upgrading because i can't use it on newer versions. So i just wanted to know if you would continue working on it. Thanks again.

**Comment by IndrekHaav** [comment]
> @yeupou are you sure the app is working for you on NC 28?

I set up a NC28 dev environment and made the change suggested by @PeterLue above, but the app isn't working, the Metadata tab doesn't show up in the sidebar. Looks like front-end changes are needed as well, but I'm not familiar enough with Nextcloud app development to take a crack at it.

FWIW, Nextcloud 28 API changes are documented here: https://docs.nextcloud.com/server/28/developer_manual/app_publishing_maintenance/app_upgrade_guide/upgrade_to_28.html

**Comment by jgrete** [comment]
Oh yes, pleeease, add 28.x compatibility. Without I will not update to NC 28.x.x because I love your app!
