### ISSUE TITLE
Title Field Appears Cut At Special Char

### ISSUE THREAD

**Issue by soloam** [gino0631/nextcloud-metadata#11]
I noticed that the metadata title field (at least I only noticed in this one) appears cut, only displaying at the first special character, for example:

If a photo contains the Metadata Title "Viágem" (trip in Portuguese), in the Nextcloud only appears "ágem", and If I have "México" it appears "éxico". And funny, if I have "Viágem México" it appears "ágem México".

Thank You

**Comment by gino0631** [comment]
This is caused by a silly bug in XML parsing, which affects all XMP metadata. It will be fixed in the next release.

**Comment by gino0631** [comment]
Should be fixed in the latest release.
