### ISSUE TITLE
Click on last files in the list removes DOM files-list__row items from the list

### ISSUE THREAD

**Issue by printminion-co** [gino0631/nextcloud-metadata#111]
Steps to reproduce:

- click on last N-files in the list. Observe upper files-list__row DOM nodes are removed. See  [2024-06-03_17.03.53.webm](https://github.com/gino0631/nextcloud-metadata/assets/145785698/3566f48a-ae72-4deb-901a-7db11a0d7153)

tested with:
- v0.20.0 715f843
- on stable29 137d4617
- browser Chrome v125.0.6422.112 (Official Build) (64-bit)

**Comment by gino0631** [comment]
Unable to reproduce. Which Nextcloud version are you using? Also, does the same behaviour can be observed with Metadata app disabled, and, for example, with Activity tab open?

**Comment by printminion-co** [comment]
- tested with:
- v0.20.0 715f843
- on stable29 137d4617

- disabling Metadata app removes the scrolling (to clicked file item) and the bug

**Comment by gino0631** [comment]
> * disabling Metadata app removes the scrolling (to clicked file item) and the bug

Other sidebar tabs (Activity, for example) are still present?

**Comment by printminion-co** [comment]
Issue can be closed 
...probably will can close the issue.
looks like https://github.com/nextcloud/server/releases/tag/v29.0.1 has a problem

**Comment by gino0631** [comment]
OK, then there's nothing we can do here.
