### ISSUE TITLE
PHP 7.2 support

### ISSUE THREAD

**Issue by MeiRos** [gino0631/nextcloud-metadata#19]
"This app cannot be installed because the following dependencies are not fulfilled:

PHP with a version lower than 7.1 is required."

Why 7.2 is not supported? I have PHP 7.2.8 and to me it looks like working. (see attached image) Using Samsung S8 with Brave browser. 

![screenshot_20180813-192021_brave](https://user-images.githubusercontent.com/17142569/44044463-4fe4eaf6-9f2e-11e8-82fc-aeaef5ddc684.jpg)

**Comment by gino0631** [comment]
I'll take a look. Last time I was testing lots of tests were failing.

**Comment by gino0631** [comment]
With PHP 7.2.9 there are cases when warnings are generated, and some metadata not extracted (for example, from [this image](https://github.com/gino0631/nextcloud-metadata/blob/master/tests/files/IMG_20170626_181110_XMP.jpg)), probably because of [this bug](https://bugs.php.net/bug.php?id=75785).

**Comment by MeiRos** [comment]
Tested that example image. First it looked ok.
Title:	Roses
Description:	Yellow roses in a park
People:	Rose2, Rose1
Tags:	Rose/Rose1, Rose/Rose2
Keywords:	Rose, Rose1, Rose2
Dimensions:	96 x 128
Camera used:	Xiaomi MI 6
Software:	Shotwell 0.26.3
GPS coordinates:	N 51° 31' 31.58" W 0° 9' 34.05"
GPS altitude:	0 m
Location:	Sussex Place, Lontoo, Yhdistynyt kuningaskunta

But there were warnings in the log. 

exif_read_data(IMG_20170626_181110_XMP.jpg): Process tag(x0211=YCbCrCoeffi): Illegal components(0) at /home/path/to/mydomain.com/public/apps/metadata/lib/Controller/MetadataController.php#158

PHP 7.2.10

**Comment by gino0631** [comment]
When I was testing, some metadata was missing as well. If that was corrected in PHP 7.2.10, and what we have now are just warnings, I will take a look again.

**Comment by MeiRos** [comment]
Sorry! My mistake!
Those are errors not warnings.

**Comment by gino0631** [comment]
It is essential that the output (the metadata you see) remains the same. If this is the case, with just some logged warnings or errors we can move forward. However, if the functionality is affected, I would like these issues to be addressed first.

**Comment by MeiRos** [comment]
Full metadata from the pic. 
```
TAG_IMAGE_WIDTH: 96
TAG_IMAGE_LENGTH: 128
TAG_COMPRESSION: 6
TAG_IMAGE_DESCRIPTION: Yellow roses in a park
TAG_MAKE: Xiaomi
TAG_MODEL: MI 6
TAG_ORIENTATION: 0
TAG_X_RESOLUTION: 72/1
TAG_Y_RESOLUTION: 72/1
TAG_RESOLUTION_UNIT: 2
TAG_SOFTWARE: Shotwell 0.26.3
TAG_DATE_TIME: 
TAG_JPEG_INTERCHANGE_FORMAT: 1082
TAG_JPEG_INTERCHANGE_FORMAT_LENGTH: 6064
TAG_EXPOSURE_TIME: 0.0015408320493066256
TAG_F_NUMBER: 1.8
TAG_EXPOSURE_PROGRAM: 0
TAG_ISO_SPEED_RATINGS: 100
TAG_EXIF_VERSION: 0220
TAG_DATE_TIME_ORIGINAL: 
TAG_DATE_TIME_DIGITIZED: 
TAG_COMPONENTS_CONFIGURATION: ???
TAG_SHUTTER_SPEED_VALUE: 9342/1000
TAG_APERTURE_VALUE: 169/100
TAG_METERING_MODE: 2
TAG_LIGHT_SOURCE: 0
TAG_FLASH: 16
TAG_FOCAL_LENGTH: 382/100
TAG_SUB_SEC_TIME: 947876
TAG_SUB_SEC_TIME_ORIGINAL: 947876
TAG_SUB_SEC_TIME_DIGITIZED: 947876
TAG_FLASHPIX_VERSION: 0100
TAG_COLOR_SPACE: 1
TAG_PIXEL_X_DIMENSION: 96
TAG_PIXEL_Y_DIMENSION: 128
TAG_SENSING_METHOD: 2
TAG_SCENE_TYPE: ?
TAG_EXPOSURE_MODE: 0
TAG_WHITE_BALANCE: 0
TAG_FOCAL_LENGTH_IN_35_MM_FILE: 27
TAG_SCENE_CAPTURE_TYPE: 0
TAG_GPS_LATITUDE_REF: N
TAG_GPS_LATITUDE: 51/1,31/1,315836/10000
TAG_GPS_LONGITUDE_REF: W
TAG_GPS_LONGITUDE: 0/1,9/1,340459/10000
TAG_GPS_ALTITUDE_REF: �
TAG_GPS_ALTITUDE: 0/1000
TAG_GPS_TIME_STAMP: 17:11:01
TAG_GPS_PROCESSING_METHOD: NETWORK
TAG_GPS_DATE_STAMP: 2017
```

Are the GPS coordinates correct? I don't know how those should be. (here and in the metadata copied from the Nextcloud. Few comments above) 
Others look fine to me except the lines fully missing. There are lots of more data in the pic taken from my Nextcloud. Of course that's not the buggy example pic.

**Comment by gino0631** [comment]
Compared to PHP 7.1, Comment, Date taken, Exposure, Focal length, Metering mode, and Flash mode are missing.

**Comment by MeiRos** [comment]
@snopy234
Still no fix.
If you want to use it with php 7.2 you have to edit appinfo/info.xml max php to 7.2.

**Comment by realies** [comment]
Is it likely that future version of PHP would fix that?

**Comment by gino0631** [comment]
I have posted a comment to [that bug](https://bugs.php.net/bug.php?id=75785), and I suggest people experiencing the same issue (i.e. missing metadata of some pictures after switching to PHP 7.2) to vote and comment there. I'm afraid there is nothing else I can do.

**Comment by geirgp** [comment]
Why was this issue closed? I this add-on discontinued?

**Comment by gino0631** [comment]
The support for PHP 7.2 was added in 89567098c8541c10ac35b6515da7088667324066, and the new version of the app should be released within 1-3 days.
