### ISSUE TITLE
Provide the getID3 library through Composer

### ISSUE THREAD

**Issue by tcitworld** [gino0631/nextcloud-metadata#2]
To make dev install easier. Will provide PR if I find the time.

**Comment by tcitworld** [comment]
It's already in 3rd-party 🙈

**Comment by gino0631** [comment]
Currently I am using a stripped down version of getid3 provided by Nextcloud, and plans are to integrate a less stripped down version, as I need more functionality (but don't want to introduce security issues by using the entire library which appears to call external scripts etc).
