### ISSUE TITLE
Support XMP sidecar files

### ISSUE THREAD

**Issue by Whisprin** [gino0631/nextcloud-metadata#21]
Hello,

I'm using pictures in ARW format (a RAW format used by Sony cameras). For tagging I'm using Digikam, which writes the metadata to a separate file which they call "XMP sidecar".

So for each picture there's a second file which holds the metadata.
E.g.
DSC1000.ARW
DSC1000.ARW.xmp

Is it possible to support those separate XMP files too?

Ideally displaying the xmp metadata inside the details of the photo.
Or just displaying the xmp metadata for the xmp file itself.

Thanks

**Comment by gino0631** [comment]
Would it be possible to get a sample of these for testing?

**Comment by Whisprin** [comment]
XMP ([Extensible Metadata Platform](https://www.adobe.com/devnet/xmp.html)) is used by many different programs for different applications.

I attached [an XMP file*](https://github.com/gino0631/nextcloud-metadata/files/2595153/DSC03956.ARW.txt) which holds the metadata for one image. The metadata was edited using [digiKam](https://www.digikam.org/). Hence, the relevant XML tag is: `digiKam:TagsList`. There are multiple individual, hierarchical tags. In order to ensure compatibility with other programs digiKam writes their XML tags too.
Since the image file itself is not relevant for the XMP metadata file, I didn't attach it. Any file with a matching file name (DSC03956.ARW) works.

*Note: Due to Githubs limitation when uploading files, I had to rename the file from DSC03956.ARW.xmp to DSC03956.ARW.txt.

**Comment by lastzero** [comment]
We are also working on XMP support (https://github.com/photoprism/photoprism/issues/68) and collect information in our Wiki: https://github.com/photoprism/photoprism/wiki/XMP

For Go, there is https://github.com/trimmer-io/go-xmp. The PHP packages I found seem not to be well maintained. But at the end of the day it's just XML, you can easily parse it.
