### ISSUE TITLE
Metadata for RAW pictures

### ISSUE THREAD

**Issue by zian92** [gino0631/nextcloud-metadata#24]
Hi,

I have a lot of raw pictures in my cloud and cannot see the metada for them. Would love to see those infos too. 

Kind regards,
Zian

**Comment by gino0631** [comment]
Thanks for the request. #22 should implement this feature.

**Comment by gino0631** [comment]
@zian92 the new version of the app with these changes was just released - please test if it works with your RAW files as expected.

**Comment by zian92** [comment]
@gino0631 Look great. Thanks! :D
