### ISSUE TITLE
PHP version lower than 7.1 required

### ISSUE THREAD

**Issue by Greek64** [gino0631/nextcloud-metadata#26]
When I try to install and enable the app, I get following error:
```Exception: App "Metadata" cannot be installed because the following dependencies are not fulfilled: PHP with a version lower than 7.1 is required.```

But I don't want to downgrade the PHP version, since all PHP version lower than 7.1 are EndOFLife (Support until December 2018).

Can we get compatibility for higher PHP version?

**Comment by gino0631** [comment]
PHP 7.1 is already supported. Are you trying to use the app with PHP 7.2? Which version of Nextcloud are you using?

**Comment by Greek64** [comment]
Hmm, yes.
Just checked and my PHP version is ```7.2.11``` (on ```Nextcloud 14.0.3.0```).
But I use the Nextcloud Docker image, which apparently comes preinstalled with PHP version 7.2.

Would you suggest I downgrade?

**Comment by gino0631** [comment]
I would use 7.1 because of the issues described in #19. PHP 7.2 will be supported in the next release of the app, but if you want it now, there is a workaround (described in that thread as well).

**Comment by Greek64** [comment]
Thanks
