### ISSUE TITLE
Icon for Nextcloud 15+

### ISSUE THREAD

**Issue by BrookeDot** [gino0631/nextcloud-metadata#28]
Nextcloud 15 added icons to the info sidebar. The current metadata app does not have an icon making it look out of place.
<img width="460" alt="screen shot 2018-12-26 at 5 02 43 pm" src="https://user-images.githubusercontent.com/150348/50461143-157be780-0931-11e9-8acd-a20406717bc9.png">

**Comment by gino0631** [comment]
Thanks for reporting, I'll take a look.
