### ISSUE TITLE
Read XMP tags

### ISSUE THREAD

**Issue by stevenhorner** [gino0631/nextcloud-metadata#3]
I started to look at reading face tags written to photos a few weeks ago and somehow getting this into Nextcloud then I stumbled across your metadata app.

Would you be able to add the ability to read XMP tags containing face tags. Picasa, Lightroom and whole host of other software can read these. I think the exact variant is: XMP-mwg-rs.

Ideally this would be written to the database and become searchable.

**Comment by gino0631** [comment]
I'll take a look. Reading of these tags shouldn't be hard, but as for the search I'm not sure.

**Comment by gino0631** [comment]
The latest `v0.5.0` should display people tagged. Search functionality is registered as a separate issue.
