### ISSUE TITLE
Error: Illegal IFD Size

### ISSUE THREAD

**Issue by aljawaid** [gino0631/nextcloud-metadata#30]
`exif_read_data(cadix-cereal-bowl.jpg): Illegal IFD size at /home/pewsedofitsc/public_html/cloud/apps/metadata/lib/Controller/MetadataController.php#166`

Does this mean anything?

**Comment by gino0631** [comment]
Maybe a bug in PHP 7.2/7.3, as discussed in #19 (assuming that your file is correct, but metadata is not displayed properly).

Please try with PHP 7.1 and see the results.
