### ISSUE TITLE
Create release for the owncloud marketplace?

### ISSUE THREAD

**Issue by prsnbrg** [gino0631/nextcloud-metadata#34]
Hey,

your App is very nice and I use this on ownCloud.

I think this app should be made available to more people.
It would be great if you could publish the app on [https://marketplace.owncloud.com/](https://marketplace.owncloud.com/).

Let me know if I can help, e.g. more testing...

**Comment by prsnbrg** [comment]
It would be very great if you do it in the next time.

**Comment by gino0631** [comment]
Published: https://marketplace.owncloud.com/apps/metadata
Please let me know if you encounter any issues.
