### ISSUE TITLE
NC17 compatibility

### ISSUE THREAD

**Issue by herrmannsdorfer** [gino0631/nextcloud-metadata#37]
Metadata 0.9.0 does not seem NC 17 ready. The NC updater is missing an update. I am running NC 16.0.5:

![Bildschirmfoto 2019-09-30 um 10 44 18](https://user-images.githubusercontent.com/43957716/65863930-521db900-e371-11e9-845c-072b3e0a28c1.png)

**Comment by adsduarte** [comment]
Hi,
Actually I've enabled it, despite ignoring the advice that it requires Nextcloud 16 or lower and until now it seems to be working fine.
Has anyone also tried it and detected any issue or vulnerability?
Thanks.

**Comment by gino0631** [comment]
The version number was updated in c9aceccd72458412dbe804072b270fcf6264090d. I haven't found any compatibility issues. As Nextcloud 17.0.0 was released several days ago, I'll publish the updated app.
