### ISSUE TITLE
corrupt EXIF header

### ISSUE THREAD

**Issue by xsus95** [gino0631/nextcloud-metadata#38]
I got exif_read_data(P1070472.JPG): corrupt EXIF header: maximum directory nesting level reached at /var/www/nextcloud/apps/metadata/lib/Controller/MetadataController.php#215 by all of my pictures

**Comment by gino0631** [comment]
Thanks for contacting. What PHP version are you using?

**Comment by xsus95** [comment]
Version: 7.3.9

gino0631 <notifications@github.com> schrieb am Do., 3. Okt. 2019, 22:17:

**Comment by gino0631** [comment]
Most probably you are facing [this PHP issue](https://bugs.php.net/bug.php?id=75424), but it would be better to create a new bug report for them. Maybe you would like to do that?

**Comment by xsus95** [comment]
The bug you mentioned is 2017 and still active. The last entries for this were made this month. If you think it makes sense, please make a bug report. Unfortunately, I do not have much experience that I could answer questions here, so i dont want to make a new bug report. Otherwise, the ticket can be closed here.

**Comment by gino0631** [comment]
Opened, please vote or provide further comments here: https://bugs.php.net/bug.php?id=78701
