### ISSUE TITLE
Can't see ratings

### ISSUE THREAD

**Issue by timkrief** [gino0631/nextcloud-metadata#39]
Hi, thanks for this app.

I use shotwell to add ratings to my pictures. The ratings are then added as metadata. I can't see those ratings using Nextcloud and the metadata app.

If this is a bug on my end, how could I fix it. However, if ratings are not supported yet, then, this is a feature request ^^

**Comment by gino0631** [comment]
Not supported yet, I'm afraid.

**Comment by gino0631** [comment]
@timkrief would it be possible for you to test with the current master branch?

**Comment by timkrief** [comment]
Hey never tried to install apps on my own yet, I'll try that on tomorrow ;)

**Comment by gino0631** [comment]
OK @timkrief :)

**Comment by timkrief** [comment]
Ok it works perfectly for me! Nice work thank you very much! @gino0631

**Comment by gino0631** [comment]
@timkrief thanks, I'm happy it works as expected :)
