### ISSUE TITLE
Display the information in Gallery too

### ISSUE THREAD

**Issue by stevenhorner** [gino0631/nextcloud-metadata#4]
The Metadata plugin is excellent in file view but would be even more useful if it displayed in Gallery. There are lots of issues in their list where people are requesting EXIF display. For example here's an [open issue](https://github.com/nextcloud/gallery/issues/204).

**Comment by gino0631** [comment]
I agree - that would be nice.

**Comment by elpraga** [comment]
It would be nice, maybe the whole Details side pane could be incorporated. (See https://github.com/nextcloud/gallery/issues/153)

**Comment by gino0631** [comment]
Closing, as Gallery was replaced by Photos, and #70 is a separate issue for that.
