### ISSUE TITLE
iOS HEIC and HEIF

### ISSUE THREAD

**Issue by mar005** [gino0631/nextcloud-metadata#41]
Would be nice to have metadata be read for iOS photos and videos.

**Comment by gino0631** [comment]
Would it be possible for you to attach some samples of such files?

**Comment by mar005** [comment]
Sure. How about this. For privacy reasons I removed the location from EXIF but everything else is still intact.

**Comment by mar005** [comment]
Guess no link was provided. 

https://cloud.miguelarios.com/s/4cwKwMJkXYeRJ9T

**Comment by mar005** [comment]
Wrong file type

https://cloud.miguelarios.com/s/b7Q97FrQqRsKLNF

**Comment by gino0631** [comment]
The provided `20191101 1951.heic` is a JPEG indeed I'm afraid:
```
[root@centos7-test Tests]# file 20191101\ 1951.heic
20191101 1951.heic: JPEG image data, JFIF standard 1.01
```

**Comment by mar005** [comment]
So not sure if the transfer to jpeg happens by Nextcloud or what but in general the metadata is not visible in NC using the metadata plugin unfortunately

**Comment by gino0631** [comment]
Nextcloud shouldn't convert file types. And yes, HEICs are not supported by the plugin yet.
