### ISSUE TITLE
App causes exception when trying to show metadata of a certain MP3 file

### ISSUE THREAD

**Issue by erikfdev** [gino0631/nextcloud-metadata#44]
I have MP3 files created by Asunder with settings VBR 225 kbit/s.
After uploading these files to my nextcloud instance, I can play them, but when clicking the metadata tab in the sidebar, I get just a spinning wheel and and exception in the nextloud log:

```
[index] Error: Exception: null at <<closure>>

0. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 123
   OCP\AppFramework\Http\JSONResponse->render()
1. /var/www/nextcloud/lib/private/AppFramework/App.php line 126
   OC\AppFramework\Http\Dispatcher->dispatch(OCA\Metadata\Con ... {}, "get")
2. /var/www/nextcloud/lib/private/AppFramework/Routing/RouteActionHandler.php line 47
   OC\AppFramework\App::main("OCA\\Metadata\\ ... r", "get", OC\AppFramework\ ... {}, {_route: "metadata.metadata.get"})
3. <<closure>>
   OC\AppFramework\Routing\RouteActionHandler->__invoke({_route: "metadata.metadata.get"})
4. /var/www/nextcloud/lib/private/Route/Router.php line 297
   undefinedundefinedcall_user_func(OC\AppFramework\ ... {}, {_route: "metadata.metadata.get"})
5. /var/www/nextcloud/lib/base.php line 1000
   OC\Route\Router->match("/apps/metadata/get")
6. /var/www/nextcloud/index.php line 42
   OC::handleRequest()

GET /index.php/apps/metadata/get?source=%2FDocuments%2F15+-+Dana+Winner+-+Het+Kleine+Dorp.mp3
from 111.222.333.444 by xxx at 2019-12-16T12:32:04+00:00
```
(I obfuscated my user name and the IP address),

**Comment by erikfdev** [comment]
Forgot to mention: 
I run metadata app 0.10.0 in Nextcloud 17.0.1.

**Comment by gino0631** [comment]
Would it possible for you to attach a sample file?

**Comment by erikfdev** [comment]
Due to copyright issues I cannot upload the file that caused me to open this issue.
However, I managed to create a small new file that causes the same issue: test.mp3

[test.mp3.zip](https://github.com/gino0631/nextcloud-metadata/files/3992630/test.mp3.zip)

**Comment by erikfdev** [comment]
BTW, did you notice that the original repo for GetID3 has already produced new releases since 1.9.14, the one that is included in nextcloud-metadata? Maybe the fix is already present in these new releases.

**Comment by gino0631** [comment]
Thanks, I'll take a look.

**Comment by gino0631** [comment]
The problem occurs because GetID3 returns an incorrect value for Encoding tool: `audio.encoder:	LAME3.100¾4`. Yes, this problem is not present in the current version of GetID3, so the solution is to upgrade. Until then, if it is possible for you to edit the source, you can comment out this line:
https://github.com/gino0631/nextcloud-metadata/blob/51739f8f958c4ea78ff1040551e264d4cae93c94/lib/Controller/MetadataController.php#L531

**Comment by erikfdev** [comment]
Thanks! Commenting out that line fixes indeed the main problem.

I guess I leave this issue open until you have upgraded the app to a newer release of GetID3. Is that OK?

**Comment by gino0631** [comment]
Good, I'm glad it worked. Yes, let's keep it open for now.
