### ISSUE TITLE
App Sidebar not displayed

### ISSUE THREAD

**Issue by reiner-text** [gino0631/nextcloud-metadata#45]
## Steps to reproduce
1. Open Files app.
2. Select `Details` (app sidebar) of a file with metadata (EXIF, ID3).
3. Select Metadata tab.

## Expected behaviour

The metadata is displayed.

## Actual behaviour

Spinning icon with an empty sidebar, without tabs and data.

### Web server
`Apache/2.4.25 (Debian) (fpm-fcgi)`

### PHP version
`7.3.9-1+0~20190902.44+debian9~1.gbpf8534c`

### Nextcloud version
`18.0.0.7`

### Updated from an older Nextcloud
`16.0.4 … 17.0.0 … 17.0.1 … 18.0.0`

#### Mozilla Firefox
`Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:71.0) Gecko/20100101 Firefox/71.0`
#### Microsoft Edge
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36 Edg/79.0.309.54`

### Browser log
```
TypeError: "fileInfo.has is not a function"
    canDisplay tabview.js:41 [https://example.com/apps2/metadata/js/tabview.js]
    canDisplay Sidebar.vue:258 [webpack:///apps/files/src/views/Sidebar.vue]
    y Sidebar.vue:1
    gt VueJS
    y Sidebar.vue:1
    VueJS 7
    VueJS 10

vue.runtime.esm.js:1888:12
```

**Comment by gino0631** [comment]
Probably a result of nextcloud/viewer#299.

**Comment by reiner-text** [comment]
Thanks for fixing. It works for me with NC 18 Beta 4.
