### ISSUE TITLE
l10n: String "strobe return" should be "strobe"

### ISSUE THREAD

**Issue by rakekniven** [gino0631/nextcloud-metadata#46]
Hello,

Nextcloud community started to translate strings of this project to many languages.

What is "strobe return"?

https://github.com/gino0631/nextcloud-metadata/blob/eb653213350b790784b3523a79adfec331a3d5c6/lib/Service/MetadataService.php#L729

Should it be "Strobe" instead?

**Comment by rakekniven** [comment]
And we also need an explanation what "strobe" means?
Not the flash, or?

**Comment by gino0631** [comment]
I'm glad Transifex is finally working (nextcloud/docker-ci#166) :)

As for the "strobes", I was probably following [this doc](http://www.exif.org/Exif2-2.PDF), and also there are many others, e.g. https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/flash.html, though I'm open to suggestions.

**Comment by rakekniven** [comment]
Ok, I was looking at https://exiv2.org/tags-xmp-exif.html

But please do not close. Please provide a explanation what "Strobe return" means.
Without we cannot translate it.

**Comment by gino0631** [comment]
https://www.dpreview.com/forums/thread/2437711#forum-post-29643039

Or [Google](https://www.google.com/search?q=exif%20%22strobe%20return%22) for more :)

**Comment by rakekniven** [comment]
Will do.
Thank you.

Now you can close :-)

**Comment by gino0631** [comment]
@rakekniven thanks for contributing.
