### ISSUE TITLE
Upgrading to 0.11.0 on Nextcloud 17 broke the Files app

### ISSUE THREAD

**Issue by paulvt** [gino0631/nextcloud-metadata#51]
I upgraded metadata to 0.11.0 this morning on all my NC 17 instances and noticed that the Files app was broken after that.

Error from the log:
```json
{ "reqId":"x354cGv6WzBSzTj4vjM4",
  "level":3,
  "time":"2020-01-21T11:23:01+00:00",
  "remoteAddr":"XXXXXXXXX",
  "user":"XXXXXX",
  "app":"PHP",
  "method":"GET",
  "url":"\/apps\/files\/",
  "message":"Undefined variable: server at \/srv\/www\/XXXXX\/apps\/metadata\/lib\/AppInfo\/Application.php#31",
  "userAgent":"...",
  "version":"17.0.2.1"}
```

**Comment by paulvt** [comment]
For people finding this issue:
As a workaround, the app can be temporary disabled to get the Files app working again.

**Comment by gino0631** [comment]
Same as #49; should be fixed now. Please update to 0.11.1.
