### ISSUE TITLE
Trying to access array offset on value of type bool at getid3_mp3.php

### ISSUE THREAD

**Issue by Skip75** [gino0631/nextcloud-metadata#54]
Hello

I'm getting below error on my fresh install of Nextcloud.

  ```
{
  "reqId": "XiooXonRGy7mwGaRkagAAAMc",
  "level": 3,
  "time": "2020-01-24T00:12:30+01:00",
  "remoteAddr": "1.1.1.1",
  "user": "skip75",
  "app": "PHP",
  "method": "GET",
  "url": "/index.php/apps/metadata/get?source=%2FDor%20Fle%2FEA%2F3+ms+%C3%A0+4+ms%20Jaer+20%2FVID_202121_19.mp4",
  "message": "Trying to access array offset on value of type bool at /var/www/nextcloud/apps/metadata/lib/GetID3/Audio/getid3_mp3.php#1795",
  "userAgent": "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0",
  "version": "18.0.0.10",
  "id": "5e2c944627efe"
}
```

Any idea of the impact ?


> PHP 7.4.2 (cli) (built: Jan 21 2020 11:35:20) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies
>     with Zend OPcache v7.4.2, Copyright (c), by Zend Technologies

**Comment by gino0631** [comment]
Would it be possible for you to submit a sample you are getting this error with?

**Comment by Skip75** [comment]
You mean the .mp4 file ? If yes, sorry I can't share, it contains my home GPS data in file metadata + my son in the movie. :/
Maybe can I help in other way ?

**Comment by gino0631** [comment]
OK, do I understand correctly this error is happening with just this one .mp4 file? Could you please also check Nextcloud logs for more information regarding the exception?

**Comment by Skip75** [comment]
Yes it seems happening only with that file.

logs with same timestamp :

**Access.log**
```
1.1.1.1 - - [26/Jan/2020:12:16:41  0100] "GET /remote.php/dav/files/skip75/Dor Fle/EA/3 ms à 4 ms Jaer 20/VID_202121_19.mp4 HTTP/1.1" 206 1619900 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"

1.1.1.1 - - [26/Jan/2020:12:16:50  0100] "PROPFIND /remote.php/dav/files/skip75/Dor Fle/EA/3 ms à 4 ms Jaer 20/VID_202121_19.mp4 HTTP/1.1" 207 1216 "-" "Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0"
```

And in **nextcloud.log** :

```
{"reqId":"Xi11I338eEHkhKPfSSkUEQAAABQ","level":3,"time":"2020-01-26T12:16:51 01:00","remoteAddr":"1.1.1.1","user":"skip75","app":"PHP","method":"GET","url":"/index.php/apps/metadata/get?source=/Dor Fle/EA/3 ms à 4 ms Jaer 20/VID_202121_19.mp4","message":"Trying to access array offset on value of type bool at /var/www/nextcloud.d-corp.eu/apps/metadata/lib/GetID3/Audio/getid3_mp3.php#1795","userAgent":"Mozilla/5.0 (Windows NT 10.0; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.0.10"}
```

file metadata (in case it can be relevant) :

> Length:	00:02:50
> Dimensions:	1920 x 1080
> Frame rate:	30.02 fps
> Bit rate:	20290 kbps
> Android version:	9
> Video codec:	H.264 - MPEG-4 AVC (part 10) (avc1)
> Audio codec:	ISO/IEC 14496-3 AAC
> Audio channels:	3
> Audio sample rate:	48 kHz
> Audio sample size:	16 bit

I don't know where to find additional relevant logs.

**Comment by gino0631** [comment]
OK, now I understand the problem. The relevant getID3 issue is JamesHeinrich/getID3#217, and it is already fixed.

**Comment by Skip75** [comment]
Ok thanks. So fix will be included on next update ?

**Comment by gino0631** [comment]
Yes.
