### ISSUE TITLE
PHP errors after upgrade to 7.4

### ISSUE THREAD

**Issue by Baptistou** [gino0631/nextcloud-metadata#62]
After upgrade from PHP 7.3 to PHP 7.4, I have the following errors in logs.
The first error seems to be the same as #53.

```
[PHP] Error: Unparenthesized `a ? b : c ? d : e` is deprecated. Use either `(a ? b : c) ? d : e` or `a ? b : (c ? d : e)` at /homepages/36/d123456789/htdocs/apps/nextcloud/apps/metadata/lib/Service/MetadataService.php#334

GET /index.php/apps/metadata/get?source=%2FDocuments%2FVideo_Clip%2FTrackmania%2FTrackmania+2020-07-02+01-04-14.mp4
from XX.XX.XXX.XX by username at 2020-07-01T23:05:47+00:00
```

```
[PHP] Error: Undefined offset: 1 at /homepages/36/d123456789/htdocs/apps/nextcloud/apps/metadata/lib/GetID3/AudioVideo/getid3_quicktime.php#1688

GET /index.php/apps/metadata/get?source=%2FDocuments%2FVideo_Clip%2FTrackmania%2FTrackmania+2020-07-02+01-04-14.mp4
from XX.XX.XXX.XX by username at 2020-07-01T23:05:48+00:00
```

Nextcloud version 18.0.6
Metadata version 0.11.1

**Comment by gino0631** [comment]
Would it be possible for you to test with the current master branch? Or to provide a sample so I could try to reproduce?

**Comment by Baptistou** [comment]
We have reproduced the issue.
After cloning from master, only the second error is still present :

```
[PHP] Error: Undefined offset: 1 at /homepages/36/d123456789/htdocs/apps/nextcloud/apps/metadata/lib/GetID3/AudioVideo/getid3_quicktime.php#1688

GET /index.php/apps/metadata/get?source=%2FDocuments%2FVideo_Clip%2FTrackmania%2FTrackmania+2020-07-02+01-04-14.mp4
from XX.XX.XXX.XX by username at 2020-07-03T14:07:12+00:00
```

**Comment by gino0631** [comment]
I have updated GetID3 to 1.9.20.  As there were changes in the relevant code, the error should be different now (or disappear at all) - could you please test again with the current master branch?

**Comment by Baptistou** [comment]
The two errors disappeared, well done :+1: 
When the next release is planned ?

**Comment by gino0631** [comment]
@Baptistou v0.12.0 fixes just the first one, I'm afraid. The next release should be in 1-2 months, unless there is something urgent.
