### ISSUE TITLE
Empty metadata for jpeg image

### ISSUE THREAD

**Issue by powerflo** [gino0631/nextcloud-metadata#64]
The metadata tab is shown for an jpeg image but it is empty. It should contain metadata.

Nextcloud version: 18.0.5
Metadata version: 0.12.0

Nextcloud metadata, nothing is shown:
![Screenshot from 2020-07-15 21-52-10](https://user-images.githubusercontent.com/1099794/87589462-8fc3b680-c6e5-11ea-8bad-ca615c5e5cc4.png)

Actual metadata of the image:
![Screenshot from 2020-07-15 21-51-24](https://user-images.githubusercontent.com/1099794/87589464-905c4d00-c6e5-11ea-8788-ec050cda5a3b.png)

## System information
PHP Version: 7.3.19
Output of `php --ri exif`
```
Cannot load Zend OPcache - it was already loaded

exif

EXIF Support => enabled
Supported EXIF Version => 0220
Supported filetypes => JPEG, TIFF
Multibyte decoding support using mbstring => enabled
Extended EXIF tag formats => Canon, Casio, Fujifilm, Nikon, Olympus, Samsung, Panasonic, DJI, Sony, Pentax, Minolta, Sigma, Foveon, Kyocera, Ricoh, AGFA, Epson

Directive => Local Value => Master Value
exif.encode_unicode => ISO-8859-15 => ISO-8859-15
exif.decode_unicode_motorola => UCS-2BE => UCS-2BE
exif.decode_unicode_intel => UCS-2LE => UCS-2LE
exif.encode_jis => no value => no value
exif.decode_jis_motorola => JIS => JIS
exif.decode_jis_intel => JIS => JIS
```

**Comment by gino0631** [comment]
If other tabs are empty as well, you are facing this bug in Nextcloud: nextcloud/server#21239.

**Comment by powerflo** [comment]
Yes, the other tabs are empty as well (except the sharing tab)

**Comment by gino0631** [comment]
In this case I suggest to update to 18.0.6, or, if not possible, to try the workarounds provided in the comments of the relevant Nextcloud issue.
