### ISSUE TITLE
Expected parameter 1 to be an array, null given at

### ISSUE THREAD

**Issue by frlan** [gino0631/nextcloud-metadata#66]
There is an error with an automatic uploaded image from threema:

I can see in log:

`Aug 16 20:34:26 sergej Nextcloud[22070]: {"reqId":"YAyEIK0IjDTHaSZ25kf6","level":3,"time":"2020-08-16T18:34:26+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/apps/metadata/get?source=%2FUpload%2FMobil%2Fthreema-20200816-190311-4d166936ed592b9e.jpg","message":"array_merge(): Expected parameter 1 to be an array, null given at /srv/nc/apps/metadata/lib/Service/MetadataService.php#79","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.7.1"}`

Version of Metadata is 0.12.0

**Comment by gino0631** [comment]
@frlan would it be possible for you to test with the current master?

**Comment by frlan** [comment]
@gino0631  It fixed that issue, but I think not the root cause

`{"reqId":"Q9QK1CdAl010hJYEtzgK","level":3,"time":"2020-08-18T17:23:43+00:00","remoteAddr":"xxx","user":"xxx","app":"PHP","method":"GET","url":"/apps/metadata/get?source=%2FUpload%2FMobil%2Fthreema-20200817-204736-202304d84bae6930.jpg","message":"Undefined index: IFD0 at /srv/nc/apps/metadata/lib/Service/MetadataService.php#79","userAgent":"Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0","version":"18.0.7.1"}`

**Comment by frlan** [comment]
(I needed to manually patch my source here. So I only cherry-picked the link commit

**Comment by gino0631** [comment]
@frlan OK, one more commit to try.

**Comment by Skip75** [comment]
Also getting that error. Any fix expected to be release ?

**Comment by gino0631** [comment]
@Skip75 would it be possible for you to test with the current master, or the linked commits, to be sure they fix the issue?

**Comment by Skip75** [comment]
Ok. I Will wait for new error, if any (they are not enought frequent).

**Comment by Skip75** [comment]
My bad, yes you're right !
Using current master I don't have anymore errors in log.

**Comment by gino0631** [comment]
Perfect, thanks for testing!
