### ISSUE TITLE
JPG XMP Metadata not showing up

### ISSUE THREAD

**Issue by dadeppa** [gino0631/nextcloud-metadata#67]
Dear all,

we use nextcloud in our voluntary fire department to share documents and photos. Because of our historical events we want to store our whole photo archive in it and we tried to use this plugin to show XMP metadata in the browser. Unfortunately this will not work. I am not able to see any settings for the different metadata. I attached two screenshots of one example picture we want to be shown:

![2020-09-04 14_19_06-EXIF_Viewer_online](https://user-images.githubusercontent.com/29388265/92239552-840d9880-eebb-11ea-98c1-d049c4ca528c.png)
![2020-09-04 14_17_31-Metadata_shown_in_nextcloud](https://user-images.githubusercontent.com/29388265/92239545-82dc6b80-eebb-11ea-8aa9-554f50bee2ab.png)

Maybe someone can help me with this. 
Thanks in advance for your kind help!

**Comment by gino0631** [comment]
Dear @dadeppa,

Would it be possible to get that example picture for analysis?

Thank you in advance.

**Comment by dadeppa** [comment]
Dear gino,

yes, no Problem:
https://nx9932.your-storageshare.de/s/2ztF2oHCdwqwTis
I hope this works, it's the first time I use nextcloud.

I think my mate edited the picture with ACDSee - maybe this information is helpfull.

Sincerely,

dadppea

**Comment by gino0631** [comment]
Thanks! Yes, both "Caption" and "Categories" are written to the proprietary ("acdsee") XMP fields that are not (yet) supported, that's why you are not seeing them in the app.

**Comment by dadeppa** [comment]
Okay - thank you very much so far! Do you have any recommendation for an image archiving / tagging program that is capable of face recognition AND set proper tags for nextcloud metadata plugin? Unluckily we do not own a server for our own nextcloud so we can not install the face detection plugin :(

**Comment by gino0631** [comment]
From my research, it should be possible to use "Manage Metadata Presets" in ACDSee to write metadata to standard fields.

Also, I can add support for these ACDSee fields; in this case, just to clarify - what you need is "Caption" and "Categories", or are there some more?

As for the face recognition, it should be possible to run it on your computer with any suitable program (I don't have any recommendations for that, sorry) that would tag the pictures, and then upload them to your Nextcloud.

**Comment by gino0631** [comment]
As for the Categories, as I understand, there is a hierarchy, and as the app already supports `digiKam:TagsList`, I would follow the same approach to display hierarchical tags, so in your case it would look like:
![image](https://user-images.githubusercontent.com/13659309/92536811-4a35ec80-f243-11ea-9ed2-071530b3625a.png)
Does it look OK?

**Comment by dadeppa** [comment]
Hi gino!
Sorry for responding delayed and thank you for your effort. Right now we are discussing how to proceed with software and which settings for which software we may use. 
In addition to the tags we provided in the first image we are even more interessted in the way how face recognition is storing data. I will try to provide some samples asap, maybe it is the best way to take a longer look at the basics and requirements than to hurry by adding one tag by another - if you understand. 

The information you posted look OK; But i have an additional question about the "Tags" propery: Is this one single string which will be displayed or are the tags separated tag-wise by reading out the semicolon?

Best Regards!

**Comment by gino0631** [comment]
OK, please attach a sample once ready.
As for the tags, hierarchical tags would be flattened using a "/" and displayed in one line using "; " as a separator. The screenshot above corresponds to your sample. I suppose this way is better than raw XML as in your screenshots.

**Comment by archont00** [comment]
A note, if it is of any help: digiKam tries to synchronise the metadata across some "standard" proprietary XMP fields:
```
File name: 20201203-082808.jpg (XMP Schema)

>>> acdsee <<<

categories : <Categories><Category Assigned="0">presentation<Category Assigned="1">family</Category></Category></Categories>
rating : 0


>>> Adobe Photoshop <<<

Date Created : 2020-12-03T08:28:08
Urgency : 0


>>> digiKam schema <<<

Color Label : 0
Pick Label : 0
Tags List : presentation/family


>>> Dublin Core <<<

Subject : family


>>> lr <<<

hierarchicalSubject : presentation|family


>>> mediapro <<<

Catalog Sets : presentation|family


>>> Microsoft Photo <<<

LastKeywordXMP : presentation/family
Rating : 0
```
And digiKam has a user settings to give some preference over various sources (useful for newly added images):
![image](https://user-images.githubusercontent.com/937861/104837450-da043b00-58b4-11eb-92e7-5e54dd08b4bf.png)

So, the nextcloud-metadata plugin should either be configurable (what proprietary structures to show) or even better, use some logic to hide redundant data.

P.S. A similar setup exists for `Comments`, `Ratings`, `Color Label`.

**Comment by gino0631** [comment]
@archont00 thank you for the information. I have implemented support for ACDSee caption and categories. If you faced the same issue, and have a possibility to test, it would be useful to get your feedback.

The plugin does contain a logic to reconcile metadata from different fields, though it is not configurable.

**Comment by archont00** [comment]
@gino0631 For me, the current solution is sufficient, even though I can see some duplicates of tags/keywords - however, these are a result of how digiKam tries to sync data for various proprietary XMP fields, so I do not consider this a problem of nextcloud-metadata.

Now, I hope to be able to search through the metadata using nextcloud rather than being limited to digiKam on my desktop pc :-)

**Comment by gino0631** [comment]
@archont00 thank you for the information. Yes, as the software writes to different fields for compatibility, and the plugin shows them all, some duplication is possible, but logically these are different fields that may contain different values.
