### ISSUE TITLE
Supress error Messages in Log on read_exif_data 

### ISSUE THREAD

**Issue by alx-tuilmenau** [gino0631/nextcloud-metadata#68]
I've got many "PHP"-type errors in the nextcloud log, regarding read_exif_data warnings. May you can add a "@" to read_exif_data in line 159 of lib/Service/MetadataService.php to supress logging these warnings.

**Comment by gino0631** [comment]
Usage of @ operator is considered to be a bad practice, and should be in the last resort only.

Have you tried to determine the cause of these warnings? Is it a bug in PHP, or incorrect image files? Which PHP version are you using?

**Comment by alx-tuilmenau** [comment]
I know using @ is bad, but is there a another way to avoid the logging of warnings from this functions ? Nextcloud redirects these warnings to his own log as errors.

The cause of this warnings are broken image or video files. I don't know if there are variants on the exif standard or only broken image software, but users regulary upload files with broken exif data, so errors like "corrupt EXIF header: maximum directory nesting level reached" are filling up the log.

I think read_exif_data will return false in this case, which is already handled in the app.

**Comment by gino0631** [comment]
This may be caused by a bug in PHP, see #19 for example. Which version are you using?

**Comment by alx-tuilmenau** [comment]
I'm using 7.3.21.  Found https://bugs.php.net/bug.php?id=75785 . Updated PHP to 7.3.22 , maybe this will fix the problem.

**Comment by gino0631** [comment]
Just to be sure - does the update fixed the problem?

**Comment by alx-tuilmenau** [comment]
Using the sample images from the PHP bug report I get no more messages from read_exif_data. There are no log messages on read_exif_data at all after the update yesterday. 
For one of the images ( https://www.tornado.se/piwigo/tools/sample.jpg ) I got a different error:  "unpack(): Type v: not enough input, need 2, have 0 at /data/nextcloud_19/apps/metadata/lib/Service/TiffParser.php#64"

**Comment by gino0631** [comment]
@alx-tuilmenau there should be no more error messages with that sample file.
