### ISSUE TITLE
Please display  EXIF UserComment field

### ISSUE THREAD

**Issue by twanky** [gino0631/nextcloud-metadata#7]
I'm hoping to use nextcloud-metadata as part a family document archive.  

It would be useful for me to display (and search on) the EXIF UserComment field.

As different people have different requirements perhaps a method of defining which fields to include in the display would be appropriate.

**Comment by gino0631** [comment]
Thank you for using my app. 

I'll include that field in the next release. Search is registered as a separate issue (#6).

Except for the `UserComment`, is there anything else you would like to be configurable (e.g. exclude certain fields)?

**Comment by twanky** [comment]
Firstly, many thanks for writing this app and enhancing the usefulness of Nextcloud and for your speedy positive response to my suggestion.

I use Shotwell to manage scanned images before uploading to Nextcloud. In Shotwell I add nested tags to the images. GIMP image editor shows these under the 'File/Properties - Advanced' view as 

http://www.digikam.org/ns/1.0/ TagsList[]

and

http://ns.microsoft.com/photo/1.0/ LastKeywordXMP[]

and a simplified view under

Dublin Core subject[]

I confess I have no idea what these mean but my added tag information could be useful to family members looking through the documents on Nextcloud.

I hope this makes sense.

**Comment by gino0631** [comment]
Would it be possible for you to prepare a sample and attach to this issue? The picture itself is not important, it can be very small or low quality (as the other [test files](https://github.com/gino0631/nextcloud-metadata/tree/master/tests/files)), but the metadata (tags and comments) should be representative.

**Comment by twanky** [comment]
![scan-00158](https://user-images.githubusercontent.com/31386022/29969195-fe24bd9a-8f16-11e7-8774-424b12ef9135.jpeg)

Apologies for the slow response - I could not upload files at first.

The attached file is a lower resolution scan of a card from the document archive. I'm not bothered about revealing personal information from this card as all involved are long deceased. 

I have added a Title, Comment and 3 x Tags and adjusted the date of the image using Shotwell.
Title: "Funeral card for John Neville Cherry"
Comment:
---
Funeral card written by Doris Marie Cherry (nee Celand) on the death of her husband John Neville Charles Cherry.

Annotated: 1927 on reverse.
---
Tags: Celand/Doris; Cherry/Doris; Cherry/John

Date: 14 Nov 1927.

I hope this makes sense.

**Comment by twanky** [comment]
Oops - wrong button.

**Comment by gino0631** [comment]
I have implemented these features in the latest (v0.6.0) version; please test and inform if everything is as expected.

**Comment by gino0631** [comment]
Should be implemented already, so closing.
