### ISSUE TITLE
Unable to use with browsers update

### ISSUE THREAD

**Issue by harrellbm** [gino0631/nextcloud-metadata#71]
﻿I keep getting these errors when trying to open the sidebar with metadata enabled when it is disabled everything works fine
sidebar.js?v=148105a6-0:1 TypeError: fileInfo.has is not a function
    at e.canDisplay (tabview.js?v=148105a6-0:37)
    at i.canDisplay (sidebar.js?v=148105a6-0:1)
    at sidebar.js?v=148105a6-0:1
    at i.At [as _l] (sidebar.js?v=148105a6-0:1)
    at i.<anonymous> (sidebar.js?v=148105a6-0:1)
    at i.e._render (sidebar.js?v=148105a6-0:1)
    at i.r (sidebar.js?v=148105a6-0:1)
    at mn.get (sidebar.js?v=148105a6-0:1)
    at mn.run (sidebar.js?v=148105a6-0:1)
    at un (sidebar.js?v=148105a6-0:1)
2
main.js?v=148105a6-0:1 The select2 library is deprecated! It will be removed in nextcloud 19.
3
main.js?v=148105a6-0:1 $ is deprecated: The global jQuery is deprecated. It will be updated to v3.x in Nextcloud 21. In later versions of Nextcloud it might be removed completely. Please ship your own.
main.js?v=148105a6-0:1 OC.Util.relativeModifiedDate is deprecated and will be removed in Nextcloud 21. See @nextcloud/moment
sidebar.js?v=148105a6-0:1 TypeError: fileInfo.has is not a function
    at e.canDisplay (tabview.js?v=148105a6-0:37)
    at i.canDisplay (sidebar.js?v=148105a6-0:1)
    at sidebar.js?v=148105a6-0:1
    at i.At [as _l] (sidebar.js?v=148105a6-0:1)
    at i.<anonymous> (sidebar.js?v=148105a6-0:1)
    at i.e._render (sidebar.js?v=148105a6-0:1)
    at i.r (sidebar.js?v=148105a6-0:1)
    at mn.get (sidebar.js?v=148105a6-0:1)
    at mn.run (sidebar.js?v=148105a6-0:1)
    at un (sidebar.js?v=148105a6-0:1)
$e	@	sidebar.js?v=148105a6-0:1

**Comment by gino0631** [comment]
Which Nextcloud version are you using?

**Comment by harrellbm** [comment]
NextCloud 20.0.5.2 
Everything was working until today.

**Comment by gino0631** [comment]
Looks similar to #45, but it is fixed, and `fileInfo.has()` is no longer used. Have you tried clearing your browser's cache (F12, F5)? Which browser are you using?

**Comment by harrellbm** [comment]
I am using Chrome 87 mostly but also tried it on Firefox and even the Oculus browser lol.  I just cleared the caches and tried again but no luck.  I did an integrity scan of my instance and it came back with this error.  I am not quite sure how to go about fixing it and if this might be what is actually causing the problem.  I tried the occ command to update the db and the mimetype.js and they said everything was up to date.
```
The following list covers which files have failed the integrity check. Please read
the previous linked documentation to learn more about the errors and how to fix
them.

Results:
- core
	- INVALID_HASH
		- core/js/mimetypelist.js

Raw output:
Array
(
    [core] => Array
        (
            [INVALID_HASH] => Array
                (
                    [core/js/mimetypelist.js] => Array
                        (
                            [expected] => 23a3fa45757b26795f5cf8f94d9e5bce76fc916288a6458679311b312c167adcf4158ccb2c5c3db791fa0b87703b6c5863afb6c9d790b8cbac5ab3ae8c3418fb
                            [current] => 248b1c46827f16075a92457d368b5f8c1c6d39c8dc8569e248b35443ac035501b86b8f46785cc6fb3f12fc8445284829c1e27aa82097a53d2688040b1de7da26
                        )

                )

        )

)
```

**Comment by gino0631** [comment]
OK, and the version of Metadata app is the latest, 0.12.0?

**Comment by harrellbm** [comment]
Whelp I feel dumb.  I am all the way back at version 0.6.0.  I installed it through the web interface and it's never given me an option to update.  Forgive me for being so new, how do I manually update an app?

**Comment by gino0631** [comment]
If it was working until today with the same Nextcloud version, then you most probably downgraded it somehow.

Anyway, in the app list there should be an option to update, or you can try removing and installing it again.

**Comment by harrellbm** [comment]
Something seems to be going wrong with the app manager.  I just uninstalled and reinstalled metadata a few times but it still installs version 0.6.0 and I just realized that the preview generator app is back at version 1.0.0 which is super out of date.  Would you have any advice to point me in the right direction to figure that out? I really appreciate it.

**Comment by gino0631** [comment]
While it is possible to install the app manually, I'd start from checking Administration Overview screen and the logs for possible problems.

**Comment by harrellbm** [comment]
I think I made some progress.  I found in my config file an install overwrite that was forcing the version to 0.6.0.  When I removed that it no longer immediately installs the old version but flags it as incompatible.
 
![image](https://user-images.githubusercontent.com/55707292/105790828-3f55cd00-5f42-11eb-8788-7d4553ac7273.png)

A weird thing happens when I try to install using occ at first it flags it as incompatible but then it goes ahead and installs the old version.

![image](https://user-images.githubusercontent.com/55707292/105790917-63b1a980-5f42-11eb-92ef-2bf7e9ea6317.png)

I also got this error in my console log
```
[core] Info: Trusted domain error. "204.48.18.143" tried to access using "192.168.0.1:443" as host.

GET /GponForm/diag_Form?style/
from 204.48.18.143 at 2021-01-26T01:57:42+00:00
```
I have no idea how this all fits together. I tried updating and restarting my os and system packages as well but the app manager still is stuck on the old version.

**Comment by gino0631** [comment]
@harrellbm thanks for the information. It's quite difficult to guess what happened to your Nextcloud instance. Maybe try installing a fresh copy, then check for the issues, and compare the configs?

**Comment by harrellbm** [comment]
A fresh install did it!  I compared the configs and there is a new instance id and secret but not much else different.  

@gino0631 thanks for all your help!

**Comment by gino0631** [comment]
@harrellbm I'm happy you managed to fix the issue this way, though the reasons remain unclear.
