### ISSUE TITLE
Support php 8

### ISSUE THREAD

**Issue by Whisprin** [gino0631/nextcloud-metadata#72]
Please add support for php 8 to nextcloud-metadata:
> This app cannot be installed because the following dependencies are not fulfilled:
> PHP with a version lower than 7.4 is required. 

Nextcloud 21 supports php 8.

**Comment by gino0631** [comment]
@Whisprin Thank you for the information regarding PHP 8. Would it be possible for you to test with the current master?

**Comment by Whisprin** [comment]
@gino0631 Thanks, seems to work with current master.

**Comment by gino0631** [comment]
Implemented in the latest v0.13.0.
