### ISSUE TITLE
Support NC 21

### ISSUE THREAD

**Issue by tetebueno** [gino0631/nextcloud-metadata#73]
Maybe is too early to request, but let's track it somewhere.

Cheers.

**Comment by gino0631** [comment]
@tetebueno the current master branch should support NC 21 - do you have a possibility to test with it?

**Comment by neuherzk** [comment]
Hi,
I can confirm the master branch is working on NC21. THANKS!! 👍

**Comment by gino0631** [comment]
Implemented in the latest v0.13.0.

@neuherzk thanks for testing!
