### ISSUE TITLE
HEIC metadata not being pulled

### ISSUE THREAD

**Issue by invario** [gino0631/nextcloud-metadata#76]
Nextcloud 20.0.8 running on TrueNAS Core 12 in IOCage FreeBSD jail 12.2-RELEASE-p3
nginx web server v1.18.0
PHP 7.4.15
Metadata plugin 0.12

Does not seem to be pulling the data from my HEIC files from my phone.

Following files taken from my Samsung Galaxy S10+ phone and uploaded direct to my personal host for debug purposes:
http://www.crimetank.com/misc/20210221_155451.heic
http://www.crimetank.com/misc/20210221_155501.heic

Display "No metadata found".  Have checked on other files (MP4 videos and some JPG from the same phone) and it will display those.

Any input, help, or direction for further debugging/troubleshooting would be greatly appreciated!

**Comment by invario** [comment]
So after doing some research, I think the issue is that the PHP exif library does not support HEIC files yet.

imagick does, however.

Found mention of it here:
https://shkspr.mobi/blog/2020/12/coping-with-heic-in-the-browser/
[Code]
$imagick = new Imagick();
$imagick->readImage('image.heic');
$exifArray = $imagick->getImageProperties("exif:*");
var_dump($exifArray);[/code]
I'm not familiar enough with php to do this. I played around a bit and figured out that readImage should instead be readImageFile to accept a filehandle. I tried playing around with the HeicMetaData.php but I'm not knowledgeable enough to do it.

**Comment by gino0631** [comment]
Thank you for the information.

It's my bug in BMFF parsing, I'll fix it soon.

**Comment by gino0631** [comment]
@invario please test, if possible.

**Comment by invario** [comment]
Replaced file with updated one, tested a few different HEIC files including the ones above. Appears to be working, thank you!!!
