### ISSUE TITLE
Update to NextCloud 23.xx

### ISSUE THREAD

**Issue by roliverio** [gino0631/nextcloud-metadata#83]
Hi!.

Thanks for this wonderful plugin, could you please update it so it works with NextCloud 23.xx ?

Thanks in advance.

**Comment by leonardohlee** [comment]
follow up

**Comment by gino0631** [comment]
Thanks for the motivating feedback. I'll prepare the release. Meanwhile, you can try enabling the app in Apps (click Enable untested app, and then Enable). There should be no issues.

**Comment by gino0631** [comment]
Already released.
