### ISSUE TITLE
option to disable traffic to third-party servers

### ISSUE THREAD

**Issue by meonkeys** [gino0631/nextcloud-metadata#85]
I'd like to suggest an option to disable contacting third-party servers. For example, to disable reverse geocoding via Nominatim. This seems to mesh well with the general ethos of Nextcloud (e.g. privacy). Another example of preventing remote connections is the "Update avatars from social media" setting in the Contacts app.

For UI/UX, users could have a checkbox at `/settings/user/privacy` or `/settings/user/metadata` with text like `[X] Allow use of a third-party server for reverse geocoding`. English tooltip: `geographic metadata in photos will be sent to a remote server to convert latitude and longitude to a human-readable address`. 

`/settings/admin/privacy` or `/settings/admin/metadata` could have a forced or default setting, like: `[X] Allow users to enable use of a third-party server for reverse geocoding`, and perhaps a setting to control the default value. This could be similar to global hard/soft defaults in `/settings/admin/sharing`.

At the code level, the settings would be checked before performing reverse geocoding.

Personally, I *want* relevant metadata in my JPEGs (such as geo lat/long), and I also want the images & metadata to be processed locally only.

My design suggestions certainly need some tweaking, I haven't read enough of the code to know if, for example, the only 3rd party used is Nominatim for geocoding or if others are used as well. I suggest the option disables any/all traffic to other servers. I hope this gets a healthy discussion going.

**Comment by gino0631** [comment]
There is no need to open another issue for the same problem.
