### ISSUE TITLE
Does not work with image formats (.jpg, .tiff) on NAS4Free

### ISSUE THREAD

**Issue by vik021** [gino0631/nextcloud-metadata#9]
Does not work with image files on NAS4Free. Installed through OneButtonInstaller, on NAS4Free 11.1.0.4 - Atomics (build 4920).

How can I fix it, find the reason?
Screenshot:
![metadta](https://user-images.githubusercontent.com/34021686/33255145-fed9cd98-d36d-11e7-937d-707e5935cd74.png)

**Comment by vik021** [comment]
Log:
{"reqId":"XXXXXXXX","level":3,"time":"2017-11-27T07:18:01+00:00","remoteAddr":"xxx.xxx.xxx.xxx","user":"admin","app":"index","method":"GET","url":"\/nextcloud\/index.php\/apps\/metadata\/get?source=%2Fnextcloud-metadata-master%2Ftests%2Ffiles%2FIMG_20170626_181110.jpg","message":"Exception: {\"Exception\":\"Error\",\"Message\":\"Call to undefined function OCA\\\\Metadata\\\\Controller\\\\exif_read_data()\",\"Code\":0,\"Trace\":\"#0 \\\/mnt\\\/Poll\\\/www\\\/Site\\\/nextcloud\\\/apps\\\/metadata\\\/lib\\\/Controller\\\/MetadataController.php(87): OCA\\\\Metadata\\\\Controller\\\\MetadataController->readExif('\\\/mnt\\\/Stripe-Poo...')\\n#1 [internal function]: OCA\\\\Metadata\\\\Controller\\\\MetadataController->get('\\\/nextcloud-meta...')\\n#2 \\\/mnt\\\/Poll\\\/www\\\/Site\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(160): call_user_func_array(Array, Array)\\n#3 \\\/mnt\\\/Poll\\\/www\\\/Site\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Http\\\/Dispatcher.php(90): OC\\\\AppFramework\\\\Http\\\\Dispatcher->executeController(Object(OCA\\\\Metadata\\\\Controller\\\\MetadataController), 'get')\\n#4 \\\/mnt\\\/Poll\\\/www\\\/Site\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/App.php(114): OC\\\\AppFramework\\\\Http\\\\Dispatcher->dispatch(Object(OCA\\\\Metadata\\\\Controller\\\\MetadataController), 'get')\\n#5 \\\/mnt\\\/Poll\\\/www\\\/Site\\\/nextcloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(47): OC\\\\AppFramework\\\\App::main('OCA\\\\\\\\Metadata\\\\\\\\Co...', 'get', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#6 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#7 \\\/mnt\\\/Poll\\\/www\\\/Site\\\/nextcloud\\\/lib\\\/private\\\/Route\\\/Router.php(299): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#8 \\\/mnt\\\/Poll\\\/www\\\/Site\\\/nextcloud\\\/lib\\\/base.php(1004): OC\\\\Route\\\\Router->match('\\\/apps\\\/metadata\\\/...')\\n#9 \\\/mnt\\\/Poll\\\/www\\\/Site\\\/nextcloud\\\/index.php(48): OC::handleRequest()\\n#10 {main}\",\"File\":\"\\\/mnt\\\/Poll\\\/www\\\/Site\\\/nextcloud\\\/apps\\\/metadata\\\/lib\\\/Controller\\\/MetadataController.php\",\"Line\":139}","userAgent":"Mozilla\/5.0 (X11; Linux x86_64; rv:57.0) Gecko\/20100101 Firefox\/57.0","version":"12.0.3.3"}

**Comment by gino0631** [comment]
Probably that's because EXIF support for PHP is missing; this can be verified by running `php --ri exif`. If it returns `Extension 'exif' not present`, try installing EXIF package for your system by running `pkg install php71-exif` (assuming you are using PHP 7.1).

**Comment by vik021** [comment]
Thank you! Everything worked on NAS4Free version 11.1.0.4 - Atomics (build 4952), using the startup script, which checks and installs php71-exif-7.1.12. Let's see what happens after the next system update.

I spread my script, can someone help:
`
#!/bin/bash

if pkg info php71-exif-7.1.12 | grep -Eq "Version|7.1.12" ; then
        echo "php71-exif-7.1.12 Installed"
        if test -e /usr/local/lib/php/20160303/exif.so ; then
                echo "File /usr/local/lib/php/20160303/exif.so created"
                if test -e /usr/local/lib/php/extensions/no-debug-non-zts-20160303/exif.so ; then
                  echo "File /usr/local/lib/php/extensions/no-debug-non-zts-20160303/exif.so created"
                  exit 0
                else
                  ln -sf /usr/local/lib/php/20160303/exif.so /usr/local/lib/php/extensions/no-debug-non-zts-20160303/exif.so
                  /etc/rc.d/lighttpd restart
                  /etc/rc.d/websrv restart
                fi
        else
          pkg install php71-exif-7.1.12 <<EOF
y
EOF
ln -sf /usr/local/lib/php/20160303/exif.so /usr/local/lib/php/extensions/no-debug-non-zts-20160303/exif.so
        fi
else
pkg install php71-exif-7.1.12 <<EOF
y
EOF

ln -sf /usr/local/lib/php/20160303/exif.so /usr/local/lib/php/extensions/no-debug-non-zts-20160303/exif.so
/etc/rc.d/lighttpd restart
/etc/rc.d/websrv restart
fi
exit 0
`

**Comment by gino0631** [comment]
Good to hear it works, and thanks for posting the solution.

The script you have posted tries to install the exact version of the package (`pkg install php71-exif-7.1.12`), not just the latest one (`pkg install php71-exif`). Why, as the latter approach looks more future-proof?

**Comment by vik021** [comment]
The fact is that the installation is performed on NAS4Free Embedded, and the installed version of the PHP does not always correspond to the latest version of the PHP-EXIF in the repository.

Sorry for my english. :-) Google translate :-)

**Comment by vik021** [comment]
A little improved the script:
#!/bin/bash

phpver=$(php -v | head -n 1 | awk '{print $2}')

installing () {
sleep 1

pkg remove php71-exif <<EOF
y
EOF

pkg install php71-exif-${phpver} <<EOF
y
EOF

sleep 1

rm -f /usr/local/lib/php/extensions/no-debug-non-zts-20160303/exif.so
ln -s /usr/local/lib/php/20160303/exif.so /usr/local/lib/php/extensions/no-debug-non-zts-20160303/exif.so
sleep 1
/etc/rc.d/lighttpd restart
/etc/rc.d/websrv restart

}

if pkg info php71-exif-${phpver} | grep -Eq "Version|${phpver}" ; then
        echo "php71-exif-${phpver} Installed"
        if test -e /usr/local/lib/php/20160303/exif.so ; then
                echo "File /usr/local/lib/php/20160303/exif.so created"
                if test -e /usr/local/lib/php/extensions/no-debug-non-zts-20160303/exif.so ; then
                  echo "File /usr/local/lib/php/extensions/no-debug-non-zts-20160303/exif.so created"
                  exit 0
                else
                  installing;
                fi
else
installing;

fi
else
installing;
fi

exit 0
