### ISSUE TITLE
Compatibility with Photo 2.0 from Nextcloud 25.x

### ISSUE THREAD

**Issue by koying** [gino0631/nextcloud-metadata#91]
For whatever reas-on, the metadata tab does not show up in the photo app, but correctly in files:

## Files

![image](https://user-images.githubusercontent.com/164740/201360016-9072cda6-8121-46ff-b5bd-ece7635b9253.png)

## Photos

![image](https://user-images.githubusercontent.com/164740/201359887-67b847db-416a-4f34-b3de-4103ee336af1.png)

**Comment by gino0631** [comment]
@koying thanks for the information and the screenshots, but it sounds like a duplicate of #70

**Comment by koying** [comment]
Oh, likely. I somehow assumed it was due to the new app.
I'll close this one then, sorry for the noise.

**Comment by gino0631** [comment]
@koying thanks for the ping!
