### ISSUE TITLE
Metadata tab on photo sidebar 

### ISSUE THREAD

**Issue by Lorthiz** [gino0631/nextcloud-metadata#93]
Right now metadata tab is only available from file explorer, but since version 25 Nextcloud improved Photos view/section a lot and it also has sidebar feature for currently zoomed photo. It would be great to have access to metadata there instead of looking for a specific photo inside file explorer.

**Comment by gino0631** [comment]
@Lorthiz thanks, though it sounds like a duplicate of #70. I agree it would be nice, and will try to implement.
