### ISSUE TITLE
Fails to read Jamendo-encoded MP3 files

### ISSUE THREAD

**Issue by filmfreedom-org** [gino0631/nextcloud-metadata#94]
Nextcloud v25
MP3 Files - Origin Jamendo
Metadata app v0.17.0

I've tested this on MP3 files from several sources, but it seems to hang on attempting to read metadata from Jamendo's MP3 files (which is unfortunate, because a LOT of the files I want to index come from there). I have no problem reading files encoded by Audacity or other LAME sources.

As a possible clue, here's the output from ffprobe on one of these files. I'm not sure what other info to provide, but you can get a copy of this file from the verification link listed in the metadata.

$ ffprobe -hide_banner "01_-_Nylon_-_5'10_-vol_3.mp3"
Input #0, mp3, from '01_-_Nylon_-_5'10_-vol_3.mp3':
  Metadata:
    title           : Nylon - 5'10 -vol 3
    album           : Direction Orient
    track           : 1/14
    copyright       : 2007 J M F. Licensed to the public under http://creativecommons.org/licenses/by-sa/3.0/ verify at http://www.jamendo.com/album/8924/
    artist          : J M F
    encoded_by      : Jamendo : http://www.jamendo.com/ | LAME
    TLEN            : 310000
    TOFN            : 01 - Nylon - 5'10 -vol 3.mp3
    creation_time   : 2008-12-16
    TDOR            : 2007-10-10
    comment         : http://www.jamendo.com/
    genre           : Ambient
    http://www.jamendo.com/: http://www.jamendo.com/
    date            : 2007
  Duration: 00:05:09.05, start: 0.025056, bitrate: 205 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 204 kb/s
    Metadata:
      encoder         : LAME3.96r
    Side data:
      replaygain: track gain - -0.800000, track peak - unknown, album gain - unknown, album peak - unknown, 
    Stream #0:1: Video: png, rgba(pc), 88x31 [SAR 2835:2835 DAR 88:31], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      title           : http://creativecommons.org/licenses/by-sa/3.0/
      comment         : Other
    Stream #0:2: Video: png, rgb24(pc), 200x50, 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      title           : http://www.jamendo.com
      comment         : Lyricist/text writer
    Stream #0:3: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 400x400 [SAR 150:150 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic)
    Metadata:
      title           : J M F : Direction Orient
      comment         : Cover (front)

**Comment by gino0631** [comment]
Thanks for the report. I have downloaded the "Nylon_-_5'10_-vol_3_-_J_M_F.mp3" file, but couldn't reproduce the issue:
![image](https://user-images.githubusercontent.com/13659309/210435526-87b3d1cd-5c19-4697-a4d5-73b618af3db6.png)

Maybe there is something relevant in the logs of your Nextcloud instance?

**Comment by filmfreedom-org** [comment]
I'll try some experiments. The files I have are old. I suppose Jamendo might have changed their encoder since then. Alternatively, it might have something to do with object storage (although other MP3s worked). Thanks for testing it!

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by gino0631** [comment]
> Jamendo might have changed their encoder since then

Might be - `LAME3.98r` in my sample, `LAME3.96r` in yours.

In any case, first I need a sample to reproduce the problem. Second, I would check with getID3(), as file parsing is done by it in this case - maybe the problem was already discovered and fixed.

**Comment by gino0631** [comment]
@filmfreedom-org do we have a sample MP3 to work with? Also, it's worth checking with the latest Metadata app v0.18.0 if the issue is still present, as I have updated getID3 library.

**Comment by filmfreedom-org** [comment]
@gino0631 
Here's one of the older MP3s from Jamendo (I picked one with a "CC-BY" license, BTW -- "JMF" is the artist, from  album #10703).  Just verified that this does have the problem with  Nextcloud Hub  25.0.2, Metadata 0.17.0.

Upgraded to Metadata 0.18.0 and tried again. Still not reading the metadata.

I tried to upload this MP3 file (had to make a zip). But perhaps I can direct-share it from my Nextcloud (I haven't actually used it much, so it may or may not work):

[https://studio.filmfreedom.net/s/edqYWqHjdtxkHZm](Vox Synthe - JMF - Nextcloud Share)

[14_-_Vox_synthe_-_vol_6_-_2'26.mp3.zip](https://github.com/gino0631/nextcloud-metadata/files/11130948/14_-_Vox_synthe_-_vol_6_-_2.26.mp3.zip)

**Comment by gino0631** [comment]
@filmfreedom-org thanks, now I can reproduce the issue.
