### ISSUE TITLE
audio sampe rate and size not correct

### ISSUE THREAD

**Issue by derwotograf** [gino0631/nextcloud-metadata#96]
I have several video files (mp4 container) which show not correct metadata. As shown in the image attached the audio section is complete off. 

<img width="390" alt="Bildschirmfoto 2023-01-18 um 12 03 50" src="https://user-images.githubusercontent.com/66261502/213155805-a7110254-3b3b-45b0-8fb4-9dcd0c2d663a.png">

this is the metadata shown in mediainfo:

<img width="656" alt="Bildschirmfoto 2023-01-18 um 12 06 52" src="https://user-images.githubusercontent.com/66261502/213156131-37bcf8b7-54b7-4f0c-8502-4c68ea7ee031.png">

Insite Resolve I did set the audio settings to 24 bit and 48kHz sample rate.

**Comment by gino0631** [comment]
Thanks for the report. Would it be possible for you to provide a sample of such video file for analysis and testing?

**Comment by derwotograf** [comment]
sure. I've prepared a sample video file for download.

https://redroot.xyz/index.php/s/gQwgf33tRJjwC4z

let me know if you need anything else I can provide.

**Comment by gino0631** [comment]
@derwotograf I have created an issue in the upstream library

**Comment by gino0631** [comment]
@derwotograf of course it is not fixed yet, I have just created the issue in getID3 project (link above). If they need something like additional samples, or have questions, it would be nice if you could contribute there. Once they fix it, I'll integrate the changes.
