### ISSUE TITLE
Division by zero for some pictures when reading metadata

### ISSUE THREAD

**Issue by tuomaskivio** [gino0631/nextcloud-metadata#97]
![image](https://user-images.githubusercontent.com/40836426/216372913-74853e45-3a56-4c20-845c-245bbc30dec6.png)

For some pictures reading metadata gets stuck and Nextcloud log shows error:
`Exception: Division by zero in file '/var/www/nextcloud/apps/metadata/lib/Service/MetadataService.php' line 799`

Easy fix would be to add `$matches[2] != 0` on [line 798](https://github.com/gino0631/nextcloud-metadata/blob/2df7b090b7a5859fc39aaf596ed89968b69ff94d/lib/Service/MetadataService.php#L798), but in this case the exposure would then show 0/1000 sec, so maybe some extra handling should be added for missing or invalid metadata.

One of the pictures which causes the error: [IMG_20200112_125337.jpg](https://cloud.kivio.fi/s/5JwNeadX9HNpab6)

**Comment by gino0631** [comment]
Can't get the picture, it says "Forbidden". Maybe you could attach it here?

**Comment by tuomaskivio** [comment]
> Can't get the picture, it says "Forbidden". Maybe you could attach it here?

Of course
![IMG_20200112_125337](https://user-images.githubusercontent.com/40836426/216376601-f134186b-9998-4cfe-8765-d0f765f9c335.jpg)

**Comment by gino0631** [comment]
@tuomaskivio perfect, I'll take a look.
